### ISSUE TITLE
Trying to play video by URL

### ISSUE THREAD

**Issue by amohiy** [kaltura/playkit-js-cast-receiver#26]
Hi, 
i want to create a kaltura custom receiver that play a content using both the entry id and the video url here is the code for doing that:

```
playerManager.setMessageInterceptor(cast.framework.messages.MessageType.LOAD, requestData => {
   
    requestData.media.customData = requestData.media.customData || {};
    if (requestData.media.customData.embedConfig
            && requestData.media.customData.embedConfig.flashVars
            && requestData.media.customData.embedConfig.flashVars.proxyData
            && requestData.media.customData.embedConfig.flashVars.proxyData.initObj
            && requestData.media.customData.embedConfig.flashVars.proxyData.initObj.externalContent){

        requestData.media.customData.mediaConfig = requestData.media.customData.mediaConfig || {};
        requestData.media.customData.mediaConfig.sources = requestData.media.customData.mediaConfig.sources || {};
        requestData.media.customData.mediaConfig.plugins = requestData.media.customData.mediaConfig.plugins || {};
        requestData.media.customData.mediaConfig.sources.hls = [
            {
                mimetype: 'application/x-mpegurl',
                url: requestData.media.customData.embedConfig.flashVars.proxyData.initObj.externalContent
            }
        ]

        // requestData.media.customData.mediaConfig.playback = requestData.media.customData.mediaConfig.playback || {};
        // requestData.media.customData.mediaConfig.playback.autoplay = true


    } else {
        requestData.media.customData.mediaInfo = {
            entryId: requestData.media.contentId,
            formats:["Web New"]
        };
    }

    // Must return the manipulated data to the receiver default load handler!
    return receiver.onLoad(requestData);
});
```

but the content plays only using the entry id. And doesn't play  using the url.

Also when i enable the autoplay i get this error

```
cast_receiver_framework.js:293 Uncaught (in promise) Error: Tracks info is not available.
    at yp (cast_receiver_framework.js:293)
    at xp._.h.getTracks (cast_receiver_framework.js:744)
    at t.value (cast-engine.js:328)
    at t.value (cast-engine.js:134)
    at t.value (player.js:1984)
    at t (player.js:530)
    at player.js:535
    at middleware.js:69
    at e.value (middleware.js:86)
    at e.value (middleware.js:67)
yp @ cast_receiver_framework.js:293
_.h.getTracks @ cast_receiver_framework.js:744
value @ cast-engine.js:328
value @ cast-engine.js:134
value @ player.js:1984
t @ player.js:530
(anonymous) @ player.js:535
(anonymous) @ middleware.js:69
value @ middleware.js:86
value @ middleware.js:67
value @ playback-middleware.js:49
value @ player.js:535
value @ player.js:547
r @ player.js:1925
(anonymous) @ player.js:1898
Promise.then (async)
value @ player.js:1896
value @ player.js:489
value @ kaltura-player.js:178
value @ kaltura-player.js:90
(anonymous) @ receiver-manager.js:77
value @ receiver-manager.js:65
value @ receiver-manager-api.js:38
(anonymous) @ index.js:92
(anonymous) @ cast_receiver_framework.js:397
_.h.fr @ cast_receiver_framework.js:854
Lp.w @ cast_receiver_framework.js:752
aj @ cast_receiver_framework.js:168
bj @ cast_receiver_framework.js:167
_.h.rh @ cast_receiver_framework.js:561
_.h.Fj @ cast_receiver_framework.js:518
ye @ cast_receiver_framework.js:82
_.h.dispatchEvent @ cast_receiver_framework.js:504
_.h.Wm @ cast_receiver_framework.js:515
ye @ cast_receiver_framework.js:82
_.h.dispatchEvent @ cast_receiver_framework.js:504
Cf @ cast_receiver_framework.js:96
_.h.cn @ cast_receiver_framework.js:514

```

here is the HTML to: 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js"></script>
    <script src="//cdnapisec.kaltura.com/p/{partner_id}/embedPlaykitJs/uiconf_id/{id}"></script>


</head>
<body>
<cast-media-player/>
<script type="application/javascript" src="index.js"></script>
</body>
</html>
```

Thanks,
Ahemd

**Comment by kaltura-hooks** [comment]
Hi @amohiy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amohiy** [comment]
Any help please ?

**Comment by OrenMe** [comment]
Hi @amohiy are you a kaltura client? are you also using the client side player?
We support playing external content on our sender side and passing it to our receiver side, so not clear why you are adding this code in the LOAD message interceptor

**Comment by amohiy** [comment]
hi, 
Thanks for replying. yes I am using kaltura's frameworks in sending and receiving for both iOS and Android. can u provide me with an example for  playing external contents on the receiver.
And yes I am a kaltura client. 

thanks in advance,
Ahmed

**Comment by OrenMe** [comment]
Hi @amohiy, can you please open a support ticket in the internal system.
